# Lab Task 01

Write a function to return True if the first and last number of a given list is same. If numbers are different then return False.

In [2]:
import numpy as np

# Given:
numbers_x = [10, 20, 30, 40, 10]
numbers_y = [75, 65, 35, 75, 30]

# Expected Output:
# Given list: [10, 20, 30, 40, 10]
# result is True

# numbers_y = [75, 65, 35, 75, 30]
# result is False


def Func(arr):
    return arr[0] == arr[(len(arr) - 1)]

print(Func(numbers_x))
print(Func(numbers_y))

True
False






# Lab Task 02

Create two NumPy arrays of the same shape and perform element-wise addition on them.

Calculate the element-wise product of two NumPy arrays.

In [19]:
#code here

one = np.arange(0, 9)
one = one.reshape(3, 3)

two = np.arange(9, 18)
two = two.reshape(3, 3)

final  = one + two

final

array([[ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

# Lab Task 03

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [26]:
#code here

arr = np.arange(0,12)
arr = arr.reshape(3, 4)

print(arr)

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])

final = np.concatenate((A, B), axis = 0)
print(final)

final = np.concatenate((A, B), axis = 1)
print(final)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


# Lab Task 04




## Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.


In [33]:
products = {
    1: 'Laptop',
    2: 'Headphones',
    3: 'Mouse'
}
shopping_cart = {}

print('Welcome to the Online Store!')
print('Available products:')
for key, value in products.items():
    print(f'{key}: {value}')

while True:
    choice = input("Enter the number corresponding to the product (press 'q' to quit): ")

    if choice.lower() == 'q':
        break

    try:
        choice = int(choice)
        if choice not in products:
            print('Please enter a valid product number.')
            continue
        product_name = products[choice]
        
        if product_name in shopping_cart:
            shopping_cart[product_name] += 1
        else:
            shopping_cart[product_name] = 1

        print(f'{product_name} added to the cart.')

    except ValueError:
        print('Please enter a valid product number.')

print('\nYour Shopping Cart:')
for product, quantity in shopping_cart.items():
    print(f'- {quantity} {product}(s)')

print('Thank you for shopping with us. Goodbye!')


Welcome to the Online Store!
Available products:
1: Laptop
2: Headphones
3: Mouse
Laptop added to the cart.
Headphones added to the cart.
Mouse added to the cart.
Please enter a valid product number.
Headphones added to the cart.
Laptop added to the cart.
Mouse added to the cart.
Please enter a valid product number.

Your Shopping Cart:
- 2 Laptop(s)
- 2 Headphones(s)
- 2 Mouse(s)
Thank you for shopping with us. Goodbye!


# Lab Task 05


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [35]:
#code here
def classify_emails(emails):
    imp = ['urgent', 'important', 'action required']
    promo = ['sale', 'discount', 'promotion', 'offer']
    spam = ['lottery', 'bol news department']

    temp_imp = []
    temp_promo = []
    temp_spam = []

    for i in emails:
        if any(keyword in i.lower() for keyword in imp):
            temp_imp.append(i)
        elif any(keyword in i.lower() for keyword in promo):
            temp_promo.append(i)
        elif any(keyword in i.lower() for keyword in spam):
            temp_spam.append(i)

    return temp_imp, temp_promo, temp_spam

emails = [
    'URGENT: Do the Dishes',
    'Check out our latest sale!',
    'Congratulations! You\'ve won a lottery!',
    'Important message: Please read',
    'Special offer: Buy one get one free',
    'aoa bol news department se shazir bolrha hu'
]

important, promotions, spam = classify_emails(emails)

print("Important Emails:")
print('\n'.join(important))
print("\nPromotions Emails:")
print('\n'.join(promotions))
print("\nSpam Emails:")
print('\n'.join(spam))



Important Emails:
URGENT: Do the Dishes
Important message: Please read

Promotions Emails:
Check out our latest sale!
Special offer: Buy one get one free

Spam Emails:
Congratulations! You've won a lottery!
aoa bol news department se shazir bolrha hu


# Lab Task 06

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [36]:
#code here
dictionary = {
    'hello': 'hola',
    'thank you': 'gracias',
    'please': 'por favor',
    'yes': 'sí',
    'no': 'no',
}

def lookup_translation(w):
    if w in dictionary:
        return dictionary[w]
    else:
        return 'Translation not available.'

while True:
    ch = input("Enter an English word to look up its Spanish translation (type 'q' to quit): ").lower()

    if ch == 'q':
        break

    translation = lookup_translation(ch)
    print(f"The Spanish translation of '{ch}' is '{translation}'.\n")


The Spanish translation of 'hello i am feeling thank you' is 'Translation not available.'.

The Spanish translation of 'yes' is 'sí'.

The Spanish translation of 'yes' is 'sí'.

The Spanish translation of '' is 'Translation not available.'.

The Spanish translation of '' is 'Translation not available.'.

The Spanish translation of '' is 'Translation not available.'.

The Spanish translation of '' is 'Translation not available.'.

The Spanish translation of '' is 'Translation not available.'.

The Spanish translation of '' is 'Translation not available.'.

The Spanish translation of '' is 'Translation not available.'.

The Spanish translation of '' is 'Translation not available.'.

The Spanish translation of '' is 'Translation not available.'.

The Spanish translation of '' is 'Translation not available.'.

The Spanish translation of '' is 'Translation not available.'.

The Spanish translation of '' is 'Translation not available.'.

The Spanish translation of '' is 'Translation not avai

# Lab Task 07

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [37]:
import pandas as pd

data = pd.read_csv('https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv')

data

Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [39]:
df = data['Global_Sales'].sum()
df

8920.44

In [43]:
data.loc[data['Global_Sales'].idxmax()]

Rank                     1
Name            Wii Sports
Platform               Wii
Year                2006.0
Genre               Sports
Publisher         Nintendo
NA_Sales             41.49
EU_Sales             29.02
JP_Sales              3.77
Other_Sales           8.46
Global_Sales         82.74
Name: 0, dtype: object

In [44]:
data[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].mean()

NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64

In [45]:
data.groupby('Genre')['Global_Sales'].sum().nlargest(5)

Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64

In [46]:
data.groupby('Genre')[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum()

NA_Sales  EU_Sales  JP_Sales  Other_Sales
Genre                                                  
Action          877.83    525.00    159.95       187.38
Adventure       105.80     64.13     52.07        16.81
Fighting        223.59    101.32     87.35        36.68
Misc            410.24    215.98    107.76        75.32
Platform        447.05    201.63    130.77        51.59
Puzzle          123.78     50.78     57.31        12.55
Racing          359.42    238.39     56.69        77.27
Role-Playing    327.28    188.06    352.31        59.61
Shooter         582.60    313.27     38.28       102.69
Simulation      183.31    113.38     63.70        31.52
Sports          683.35    376.85    135.37       134.97
Strategy         68.70     45.34     49.46        11.36

In [47]:
data.tail(10)

Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

In [48]:
data.groupby('Platform')['Global_Sales'].sum().nlargest(3)

Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64

In [51]:
(data.groupby('Genre')['Global_Sales'].sum() / df) * 100

Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64

In [53]:
data['NA_Sales'].corr(data['EU_Sales'])

0.767726748370264